repos:
  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        types: [python]
        args: [--config=pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.14.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        types: [python]

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        types: [python]

  # JavaScript/TypeScript/CSS/HTML/JSON/Markdown formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, css, scss, json, yaml, html, markdown]
        additional_dependencies:
          - prettier@3.5.3
        exclude: |
          (?x)^(
              pwa/node_modules/.*|
              .*\.min\.(js|css)$|
              package-lock\.json$
          )$

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  # Dockerfile linting (optional)
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [--ignore, DL3008, --ignore, DL3009]
        files: Dockerfile*