# Docker Compose configuration for building from source (development)
services:
  lanbuhandy:
    build:
      context: .
      platforms:
        - linux/amd64
    platform: linux/amd64
    ports:
      - '8080:8000'
    restart: unless-stopped
    environment:
      # Configure Bambu printers for LAN-only mode communication

      # NEW FORMAT (Recommended): Multiple printers with JSON configuration
      # Set BAMBU_PRINTERS with a JSON array of printer configurations:
      # Each printer needs: name, ip, and access_code
      # Example for multiple printers:
      # - BAMBU_PRINTERS=[{"name":"Living Room X1C","ip":"192.168.1.100","access_code":"12345678"},{"name":"Garage A1 mini","ip":"192.168.1.101","access_code":"87654321"}]
      # Example for single printer:
      # - BAMBU_PRINTERS=[{"name":"My Printer","ip":"192.168.1.100","access_code":"12345678"}]
      - BAMBU_PRINTERS=${BAMBU_PRINTERS:-}

      # Other settings
      - LOG_LEVEL=${LOG_LEVEL:-info}