services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /workspace/node_modules
      - /workspace/pwa/node_modules
    command: sleep infinity
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - PYTHONPATH=/workspace/backend
      - NODE_ENV=development
    working_dir: /workspace