services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - claude:/claude
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: sleep infinity
    ports:
      - '8000:8000'
      - '3000:3000'
      - '5173:5173'
    environment:
      - PYTHONPATH=/workspace/backend
      - NODE_ENV=development
    working_dir: /workspace
volumes:
  claude:
