services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      platforms:
        - linux/amd64
    platform: linux/amd64
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - claude:/claude
    command: sleep infinity
    ports:
      - '8000:8000'
      - '3000:3000'
      - '5173:5173'
    environment:
      - PYTHONPATH=/workspace/backend
      - NODE_ENV=development
    working_dir: /workspace
volumes:
  claude:
