name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install backend dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
        
    - name: Run Python linter (flake8)
      run: |
        python -m flake8 backend/
        
    - name: Run backend tests
      run: |
        cd backend
        python -m pytest tests/ -v --cov=app --cov-report=term-missing
        
    - name: Set up Node.js for PWA
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install PWA dependencies and build
      run: |
        cd pwa
        npm install
        npm run build
        
    - name: Build Docker image
      run: |
        docker build .