name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install system dependencies for Bambu Studio CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          binutils \
          fuse \
          libfuse2 \
          libxcb1 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-render0 \
          libxcb-shape0 \
          libxcb-sync1 \
          libxcb-util1 \
          libxcb-xfixes0 \
          libxcb-xinerama0 \
          libxcb-xkb1 \
          libxkbcommon-x11-0 \
          libxkbcommon0 \
          ca-certificates \
          gnupg \
          curl \
          wget \
          xvfb
        
    - name: Install Bambu Studio CLI
      run: |
        chmod +x scripts/install-bambu-studio-cli.sh
        sudo scripts/install-bambu-studio-cli.sh
        
    - name: Install backend dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
        
    - name: Run Python linter (flake8)
      run: |
        python -m flake8 backend/
        
    - name: Verify Bambu Studio CLI installation
      run: |
        bambu-studio-cli --help || echo "CLI help command failed, but CLI may still be functional"
        bambu-studio-cli --version || echo "CLI version command failed, but CLI may still be functional"
        
    - name: Run backend tests
      run: |
        cd backend
        # Set up virtual display for headless environment
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        # Run tests with verbose output and coverage
        python -m pytest tests/ -v --cov=app --cov-report=term-missing -s
        
    - name: Set up Node.js for PWA
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install PWA dependencies and build
      run: |
        cd pwa
        npm install
        npm run build
        
    - name: Build Docker image
      run: |
        docker build .